export const basePath = 'dashboard';
export const CREATE = 'dashboard/CREATE_DATA';
export const UPDATE = 'dashboard/UPDATE_DATA';
export const CHANGE_SUMMONER_NAME = 'CHANGE_SUMMONER_NAME';
export const SUBMIT_SUMMONER_NAME = 'SUBMIT_SUMMONER_NAME';
export const FETCH_MATCHLIST = 'FETCH_MATCHLIST';
export const FETCH_MATCHESIDS_SUCCESS = 'FETCH_MATCHESIDS_SUCCESS';
export const FETCH_DASHBOARD_FAILED = 'FETCH_DASHBOARD_FAILED';
export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS';
export const FETCH_MATCHDETAIL_SUCCESS = 'FETCH_MATCHDETAIL_SUCCESS';
export const FETCH_MATCHDETAIL_FAILED = 'FETCH_MATCHDETAIL_FAILED';
export const FETCH_SUMMONER_SUCCESS = 'FETCH_SUMMONER_SUCCESS';
export const CLEAR_MATCH_DATA = 'CLEAR_MATCH_DATA';

export const baseUrl = 'https://na1.api.riotgames.com/lol';
